name: Deploy production
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm install -g wrangler@4.43.0

      - name: Install dependencies
        run: npm install hono

      - name: Build & Deploy Worker
        id: build-and-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          environment: prod
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            LLM_TOKEN_PROD
        env:
          LLM_TOKEN_PROD: ${{ secrets.LLM_TOKEN_PROD }}

      - name: Print staging URL
        env:
          DEPLOYMENT_URL: ${{ steps.build-and-deploy.outputs.deployment-url }}
        run: echo "**URL:** [$DEPLOYMENT_URL]($DEPLOYMENT_URL)" >> $GITHUB_STEP_SUMMARY

