name: Deploy staging
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Wrangler
        run: npm install -g wrangler@4.43.0
        
      - name: Install dependencies
        run: npm install hono
        
      - name: Build & Deploy
        id: build-and-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          environment: staging
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            LLM_TOKEN
            USERNAME
            PASSWORD
        env:
          LLM_TOKEN: ${{ secrets.LLM_TOKEN_STAGING }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          
      - name: Print staging URL
        env:
          DEPLOYMENT_URL: ${{ steps.build-and-deploy.outputs.deployment-url }}
        run: echo "**URL:** [$DEPLOYMENT_URL]($DEPLOYMENT_URL)" >> $GITHUB_STEP_SUMMARY

